### ISSUE TITLE
先物公開 API がエラーになることがある

### ISSUE THREAD

**Issue by nohtaray** [techbureau/zaifapi#13]
先物公開 API に複数のパラメータを渡した場合にエラーになることがあります。
パラメータがパスに挿入される順番が不定になってしまうようです。
https://api.zaif.jp/fapi/1/last_price/1/btc_jpy
https://api.zaif.jp/fapi/1/last_price/btc_jpy/1
後者に当たった場合502が返ってきます。

```py
from zaifapi import ZaifFuturesPublicApi

futures_api = ZaifFuturesPublicApi()
futures_api.last_price(group_id=1, currency_pair='btc_jpy')
```

```
Traceback (most recent call last):
...
  File ".../lib/python3.5/site-packages/zaifapi/exchange_api/public.py", line 81, in last_price
    currency_pair=currency_pair)
  File ".../lib/python3.5/site-packages/zaifapi/exchange_api/public.py", line 21, in _execute_api
    raise ZaifApiError('return status code is {}'.format(response.status_code))
zaifapi.api_error.ZaifApiError: return status code is 502
```

**Comment by RossyWhite** [comment]
報告ありがとうございます。
こちら確認して修正させていただきますね。

**Comment by RossyWhite** [comment]
@nohtaray 

アップデートしましたので、ご確認ください。
https://pypi.python.org/pypi/zaifapi/1.6.2

何か問題ありましたらまたお気軽にお願いいたします:D
