### ISSUE TITLE
環境によって実行するとエラーになる

### ISSUE THREAD

**Issue by bols-blue** [techbureau/zaifapi#5]
gcpのubuntuインスタンス上で実行していたのですが最初は動いていたのですが、以下のようなエラーをはくようになってしまいました。
治そうかと思ったんですが、ちょっと良くわからなかったです。
`
Traceback (most recent call last):
  File "./history.py", line 17, in <module>
    print(json.dumps(zaif.trade_history()))
  File "/home/bols/.local/lib/python2.7/site-packages/zaifapi/impl.py", line 235, in trade_history
    return self._execute_api(inspect.currentframe().f_code.co_name, schema_keys, kwargs)
  File "/home/bols/.local/lib/python2.7/site-packages/zaifapi/impl.py", line 213, in _execute_api
    header = self.get_header(params)
  File "/home/bols/.local/lib/python2.7/site-packages/zaifapi/impl.py", line 271, in get_header
    signature = hmac.new(bytearray(self._secret.encode('utf-8')), digestmod=hashlib.sha512)
AttributeError: 'NoneType' object has no attribute 'encode'
`
ちなみに手元のubuntu ノートPCでは動いています。

**Comment by bols-blue** [comment]
ちなみに2.7だけでなく3.6.1でも試しましたが同様のエラーになりました

**Comment by Akira-Taniguchi** [comment]
ZaifTradeApiのコンストラクた第二引数を指定していないのではないでしょうか

**Comment by bols-blue** [comment]
それですね。環境変数から読んでいたのをプロファイルに入れ忘れてました。
申し訳ない。クローズします。
