### ISSUE TITLE
zaifapiをインポートできないエラーがでました。

### ISSUE THREAD

**Issue by hamuchu** [techbureau/zaifapi#9]
zaifapiをインポートすると以下のようなバグがでます。
pip install zaifapiでインストールしました。
```
>>> from zaifapi import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/anaconda2/envs/xgboost/lib/python2.7/site-packages/zaifapi/__init__.py", line 1, in <module>
    from .exchange_api import *
  File "/home/username/anaconda2/envs/xgboost/lib/python2.7/site-packages/zaifapi/exchange_api/__init__.py", line 5
    class ZaifExchangeApi(ZaifApi, metaclass=ABCMeta):
                                            ^
SyntaxError: invalid syntax
```

理由は不明ですが、もし何か解決策がありましたら教えて頂けると助かります。

**Comment by RossyWhite** [comment]
@hamuchu 

報告ありがとうございます。

おそらくpython2系から使用していることが原因かと思われます。
さっき試したら同じエラーが出ていました。。。

python2系は今後サポートされない予定ですので、
Python3からご利用くださいまし。m(_ _)m

分かりづらかったですね。。。すみません。
READMEにもそのように記載しておきます。

**Comment by RossyWhite** [comment]
動かなかったらまたお気軽におっしゃってください。

**Comment by hamuchu** [comment]
迅速な回答どうもありがとうございます。

そうなんですね。Python3から使うと良いんですね。

zaifapiとても使いやすくて重宝しております。
